config/routes.rb
WaveCloud::Application.routes.draw do
  

  get "audio/index"
  get "audio/new"
  get "songs/play"
  get "users/filterUsers"
  match "songs/:id/audioimage", :to => "songs#audioimage"
  get "songs/showUsersSongs"
  root :to => 'sessions#new'
  
  resources :users
  resources :songs, :only =>[:index, :destroy, :edit, :update, :show] do
    resources :song_comments
  end
  resources :sessions, :only => [:new, :create, :destroy]
  
  match '/signup', :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match "upload", :to => 'upload#index'
  post "upload/uploadFile"

  get "audio_image_processor/image_processor"
  get "audio_converter/convert_new_audiofiles"

end

app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :user
  belongs_to :audio
  has_many :song_comments, :dependent => :delete_all
  
  validates(:name, :presence => true)
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  before_filter :require_login
  
  def index
    @songs = Song.all
  end
  
  # Renders the Songlist of the User with id params[:id]
  # Usually called by ajax
  def showUsersSongs
    @songs = Array.new
    @user = User.where(:id => params[:id]).first
    @user.songs.each do |song|
      @songs << song
    end
    respond_to do |format|
      format.html
      format.js
    end
  end

 # An ajax call of this method only renders the comments for a Song (views/songs/show.js.erb).
 # The Song id has to be in params[:id].
 # If this method is called normal (views/songs/show.html.erb) the Player will be rendered
 # as well with the given Song as source.
  def show
     path=""
     @song = Song.where(:id=>params[:id]).first
     @user = @song.user
     @audio = @song.audio
     @audio_path = @audio.id.to_s+".mp3"
     @audioimage_path = audioimagepath(@audio)
     respond_to do |format|
       format.html
       format.js
     end
  end

  def edit
    @song = Song.find(params[:id])
    respond_to do |format|
       format.html
       format.js
     end
  end

  def update
    @song = Song.find(params[:id])
    if @song.update_attributes(params[:song]) then
      redirect_to(@song, :notice => 'Song was successfully updated.')
    else
      render :action => "edit"
    end
  end

  def destroy
    @song = Song.find(params[:id])
    @song.destroy
    flash[:notice] = 'Song was successfully deleted.'
    redirect_to(songs_url)
  end
 
 # An ajax call of this method only renders the player (views/songs/play.js.erb).
 # The Song id has to be in params[:id]. Else there is no
 # source file for the player
 # If this method is called normal (views/songs/play.html.erb) the comments of
 # the Song will be rendered as well.
  def play
    path=""
     @song = Song.where(:id=>params[:id]).first
     @audio = @song.audio
     @audio_path = @audio.id.to_s+".mp3"
     @audioimage_path = audioimagepath(@audio)
     respond_to do |format|
       format.html
       format.js
     end
  end

  def audioimage
     @song = Song.where(:id=>params[:id]).first
     @audio = @song.audio
    render :text => audioimagepath(@audio)
  end

private

  def audioimagepath(audio)
    
    if audio.nil? || audio.imageprocessed == false
	"std_audioimage.png"
    else
	audio.id.to_s+".png"
    end
  end
end

app/helpers/songs_helper.rb
module SongsHelper

end

app/views/songs/_edit.html.erb
<h1>Song Metadata</h1>

<%= form_for(@song, :remote => true) do |f| %>
 <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :filename %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :artist %><br />
    <%= f.text_field :artist %>
  </div>
  <div class="field">
    <%= f.label :album %><br />
    <%= f.text_field :album %>
  </div>
  <div class="field">
    <%= f.label :year %><br />
    <%= f.text_field :year %>
  </div>
  <div class="field">
    <%= f.label :tracknumber %><br />
    <%= f.text_field :tracknum %>
  </div>
  
  <div class="actions">
    <%= f.submit "Save" %>
  </div>
  
<% end %>

app/views/songs/_index.html.erb
<h1>
  <% if @user == current_user #differ between own and other's Songlist
  %>
    My
  <% else %>
      <%= @user.nickname + "'s " %>
  <% end %>
  Songlist
</h1>

<input id="search" type="text"/>

<div class="songlist">
  <table>
    <tr>
      <th>Songname</th>
      <th>Artist</th>
      <th>Album</th>
      <th>&nbsp;</th>
    </tr>
      <%
      #change all nil-entries to avoid errors
      @songs.each do |song|
        song.title = "unknown title" if song.title.nil?
        song.artist = "unknown artist" if song.artist.nil?
        song.album = "unknown album" if song.album.nil?
        song.tracknum = "" if song.tracknum.nil?
      end
      @songs.sort_by { |a| [a.artist, a.album, a.tracknum, a.title]
                   }.each do |song|
      %>
        <tr class="songrow">
          <td>
            <%=link_to song.title, {:controller => "songs", :action => "play", :id => song}, :remote => true%>
          </td>
          <td><%= song.artist %></td>
          <td><%= song.album %></td>
          <td><%= link_to 'comments', song, :remote => true %></td>
        </tr>
      <% end %>
  </table>
</div>

<!--
  Search for a song in the songlist. Searchstring is
  the value of textfield with id 'search'
-->
<script type="text/javascript">  
  $('#search').keyup(function()
  {
    var searchString = $(this).val().toLowerCase();
    $('.songlist table .songrow').each(function()
    {
      var items = "";
      $(this).children().each(function()    //collecting all items (title, artist, album, ...) in one string
      {
        items = items + $(this).text();
      });
      items = items.toLowerCase();
      if(items.match(searchString))         //show only the matching songs
        $(this).show();
      else
        $(this).hide();

    });
  });
</script>

app/views/songs/_metainfos.html.erb
<div class="songmeta round" style="width:100%; margin-left:20px; margin-top:5px; padding-left:5px; padding-right:5px">
  <% if !@song.title.nil? && !@song.title.empty? %>
    <div class="metainfo">Title: <%= @song.title %></div>
  <% end %>
  <% if !@song.artist.nil? && !@song.artist.empty? %>
    <div class="metainfo">Artist: <%= @song.artist %></div>
  <% end %>
  <% if !@song.album.nil? && !@song.album.empty? %>
    <div class="metainfo">Album: <%= @song.album %></div>
  <% end %>
   <% if !@song.year.nil? %>
    <div class="metainfo">Year: <%= @song.year %></div>
  <% end %>
   <% if !@song.tracknum.nil? %>
    <div class="metainfo">Tracknumber: <%= @song.tracknum %></div>
  <% end %>

<% if @song.user_id == current_user.id %>
  <%= link_to "Edit", {:controller => "songs", :action => "edit", :id => @song}, :remote => true %>
  <%= link_to 'Delete', song_path(@song),
              :confirm => 'Are you sure?', :method => :delete %>
<% end %>
<%= link_to "Show Comments", @song, :remote => true %>

</div>

app/views/songs/_show.html.erb
<h2>
    Comments
    <% if @song.title.nil? %>
        <%= "for " + @song.name %>
    <% else %>
        <%= "for " + @song.title %>
    <% end %>
</h2>
<%= link_to "back to Songlist", {:controller => "songs", :action => "showUsersSongs", :id => @user.id}, :remote => true %>
<% if @song.song_comments.length > 0 then %>
    <div class="commentlist">
        <%= render @song.song_comments %>
    </div>
<% else %>
    <br/>no comments
<% end %>

<script language="Javascript">
$(document).ready(function() {  
if ($("#audioplayer").attr('songid') == <%=@song.id%>) {

$(".comment").mouseover(function(e){
  from = parseFloat($(this).attr('from'));
  to = parseFloat($(this).attr('to'));
  left = Math.round(from/audioElement.duration*100)/100*aicWidth
  right = Math.round(to/audioElement.duration*100)/100*aicWidth
  diff = right-left;
  $('#layer4').css('margin-left',Math.round(left));
  $('#layer4').css('width',Math.round(diff));
  
});

$(".comment").mouseout(function(e){

  
  $('#layer4').css('margin-left',0);
  $('#layer4').css('width',0);
  
});
}
});

</script>

app/views/songs/edit.html.erb
<%= render 'songs/edit' %>

app/views/songs/edit.js.erb
$("#main").html("<%= escape_javascript(render 'songs/edit')%>");

app/views/songs/index.html.erb
<%= render 'songs/index' %>

app/views/songs/play.html.erb
<%#= render 'songs/show' %>

app/views/songs/play.js.erb
$("#player").html("<%= escape_javascript(render '/layouts/player')%>");

app/views/songs/show.html.erb
<script type="text/javascript">
$(document).ready(function() {  
reload_image = $('#layer2 img');
var reloadCount = 0;
    if("/assets/std_audioimage.png" == reload_image.attr('src').toString()){

      var intId<%=@song.id%> = setInterval(reloadImage,3000);
      $('#layer6 img').show();

      function reloadImage(){
        
        if (reloadCount++ > 10 ){
          clearInterval(intId<%=@song.id%>);
	  $('#layer6 img').hide();
	}
 
        $.ajax({
          url: "/songs/<%=@song.id%>/audioimage",
          context: document.body,
          success: function(data){
            if("std_audioimage.png" != data.toString() ){
     	      reload_image.attr('src','/assets/'+data);
	      clearInterval(intId<%=@song.id%>);
	      $('#layer6 img').hide();
            }
          }
        });
   
      }
    }
});
</script>

<%= render 'songs/show' %>

app/views/songs/show.js.erb
$("#main").html("<%= escape_javascript(render 'show')%>");

app/views/songs/showUsersSongs.html.erb
<%= render 'songs/index' %>

app/views/songs/showUsersSongs.js.erb
$("#main").html("<%= escape_javascript(render 'index')%>");