config/routes.rb
WaveCloud::Application.routes.draw do
  

  get "audio/index"
  get "audio/new"
  get "songs/play"
  get "users/filterUsers"
  match "songs/:id/audioimage", :to => "songs#audioimage"
  get "songs/showUsersSongs"
  root :to => 'sessions#new'
  
  resources :users
  resources :songs, :only =>[:index, :destroy, :edit, :update, :show] do
    resources :song_comments
  end
  resources :sessions, :only => [:new, :create, :destroy]
  
  match '/signup', :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match "upload", :to => 'upload#index'
  post "upload/uploadFile"

  get "audio_image_processor/image_processor"
  get "audio_converter/convert_new_audiofiles"

end

app/views/layouts/_actualPlaylist.html.erb
<div class= "actualPlaylist">
  <ul>actual Playlist
    <li>Track1</li>
    <li>Track2</li>
    <li>Track3</li>
    <li>Track4</li>
    <li>...</li>
  </ul>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%=link_to "Home", root_path %></li>
      <li><%=link_to "Profile", users_path %></li>
      <li><%=link_to "Help", root_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>

<div class="bg_header">
<nav class="round">
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Help", root_path %></li>
      <% if signed_in? %>
        <li><%= link_to "Sign out", signout_path %></li>
      <% else %>
        <li><%= link_to "Sign in", signin_path %></li>
      <% end %>
    </ul>
  </nav>

  </div>

  
</header>

app/views/layouts/_menu.html.erb
<div class="usermenu span-3 round-left">
  <ul>
<li>Menu<li>

    <li><%= link_to "+ Audio", upload_path, :remote => true %></li>
    <li><%= link_to "My Audios", {:controller => "songs", :action => "showUsersSongs", :id => current_user.id}, :remote => true %></li>
    <li><%= link_to "My Profile", current_user, :remote => true%></li>
    <li><%= link_to "Other Users", users_path, :remote => true%></li>
  </ul>
</div>

app/views/layouts/_metainfos.html.erb
<div class="metainfoContainer">
  <% if !@song.title.nil? && !@song.title.empty? %>
    <div class="metainfo">Title: <%= @song.title %></div>
  <% end %>
  <% if !@song.artist.nil? && !@song.artist.empty? %>
    <div class="metainfo">Artist: <%= @song.artist %></div>
  <% end %>
  <% if !@song.album.nil? && !@song.album.empty? %>
    <div class="metainfo">Album: <%= @song.album %></div>
  <% end %>
  <div class="clear"></div>
</div>

app/views/layouts/_player.html.erb
<div id="playerContainer" class="round">
<audio id="audioplayer" controls autoplay  preload songid="<%=@song.id%>">
  <source src="<%=asset_path @audio_path%>" type="audio/mp3" />
</audio>

<div id="audioimagecontainer" class="round" style="">

<!-- background -->
<div id="layer5"></div>

<!-- fortschritt -->
<div id="layer1"></div>
 
<!-- marker -->
<div id="layer3"></div>

<!-- comment marker -->
<div id="layer4"></div>

<!-- wavemask -->
<div id="layer2">
   <%= image_tag @audioimage_path %>
</div>

<!-- loader -->
<div id="layer6">
   <%= image_tag "loading.gif" %>
</div>

</div>

<!-- metainfos -->
<div class="metainfos">
<%= render 'songs/metainfos' %>
</div>

</div>


<script language="Javascript">
var audioElement = document.getElementById('audioplayer')
var out = document.getElementById('out');
var canvasTime = $("#layer1")
var audioimagecontainer = document.getElementById('audioimagecontainer');
var aicWidth = $("#audioimagecontainer").width();


setInterval("renderCanvasMonitor()", 500);
mem_currentTime = 0;
var i = 0;
function renderCanvasMonitor () {



    if(mem_currentTime != audioElement.currentTime){
      mem_currentTime = audioElement.currentTime;
      audioLength = audioElement.duration;
      proz = (audioElement.currentTime/audioLength) + 0.002;
      canvas_size = aicWidth * proz;
      canvasTime.width(canvas_size);
    
      $('[songid_of_comment|="<%=@song.id%>"]').each(function(index) {
       
      if (audioElement.currentTime >= parseFloat($(this).attr('from')) &&
          audioElement.currentTime <= parseFloat($(this).attr('to')) ){
            $(this).css('color','#29F716');
      } else {
         $(this).css('color','#ffffff');
      }

      });

    }
  
}


</script>

<script type="text/javascript">
var from = 0;
$("#audioimagecontainer").mousedown(function(e){
  var mouseX = e.pageX - this.offsetLeft;
  from = mouseX/aicWidth
  $('#song_comment_from_duration').val(Math.round(audioElement.duration*from*100)/100);
  $('#layer3').css('margin-left',aicWidth*from);
  $('#layer3').css('width',1);

  $("#audioimagecontainer").mousemove(function(e){
  var mouseX = e.pageX - this.offsetLeft;
  var to = mouseX/aicWidth
  diff = to-from
  $('#layer3').css('width',aicWidth*diff);
  });

});


$("#audioimagecontainer").mouseup(function(e){
  var mouseX = e.pageX - this.offsetLeft;
  var to = mouseX/aicWidth
  diff = to-from
  $('#song_comment_to_duration').val(Math.round(audioElement.duration*to*100)/100);
  $('#layer3').css('width',aicWidth*diff);

  $("#audioimagecontainer").unbind('mousemove');

  if(from == to)
  {
     audioElement.currentTime = to*audioElement.duration;
  }else{

	$.facebox({  
        	loadingImage : '/assets/loading.gif',  
        	closeImage   : '/assets/closelabel.png',
		ajax: '<%= new_song_song_comment_path(@song)%>'
	}); 
  }
      
});

</script>

<!-- Comment Box -->
<script type="text/javascript">
$(document).ready(function() {
    $(document).unbind('reveal.facebox');
    $(document).bind('reveal.facebox', function() {
        $('#new_song_comment').submit(function() {  
            $.post(this.action, $(this).serialize(), null, "script");  
            $.facebox.close();
	    $("#layer3").width(0);
            return false;  
        });
	    
    });   
   
    
}); 
</script>

app/views/layouts/_playlist.html.erb
<div class="playlist round span-2 last">
  Playlist....
  <br />
</div>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'facebox', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>

<%= stylesheet_link_tag 'application', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WaveCloud</title>
  <%= render 'layouts/stylesheets' %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "facebox" %>
  <%= csrf_meta_tags %>


</head>
<body>

  <div class="container">
      
    <%= render 'layouts/header' %>
    <% if signed_in? %>
    <div id="player">
      <% if !@song.nil? %>
      <%= render 'layouts/player' %>   
      <% end %>
    </div>
    <div id="menu">
      <%= render 'layouts/menu' %>
    </div>
      <%#= render 'layouts/actualPlaylist' %>
    <% end %>
   
    <section class="span-20 round-right">
        <div id ="main">
          <% flash.each do |key, value| %>
            <div class="flash <%= key %>"><%= value %></div>
          <% end %>
  
          <%= yield %>
        </div>

    </section>

    <%# if signed_in? %>
      <%#= render 'layouts/playlist' %>
    <%# end %>

    <div class="clear"></div>

    <%= render 'layouts/footer' %>
   
    <%= debug(params) if Rails.env.development? %>

  </div>

</body>
</html>